import type { IArticle, ICategoryArticle } from "@/interfaces/article.interface";
import SamgsungA24 from '@/assets/smartphone.jpg';

export const CATEGORY_ARTICLES: ICategoryArticle[] = [
    { id: 1, name: 'Informatique', icon: 'mdi-laptop' },
    { id: 2, name: 'Electroménager', icon: 'mdi-washing-machine' },
    { id: 3, name: 'Ménage', icon: 'mdi-broom' },
    { id: 4, name: 'Meubles', icon: 'mdi-sofa' },
];

export const ARTICLES:IArticle[]=[{
    id: 1,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 510,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 50
},
{
    id: 2,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 5
},
{
    id: 3,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 5
},
{
    id: 4,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 0
},
{
    id: 5,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 10
},
{
    id: 6,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 10
},
{
    id: 7,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 0
},
{
    id: 8,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 0
},
{
    id: 9,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 0
},
{
    id: 10,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 0
},
{
    id: 11,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 0
},
{
    id: 12,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 0
},
{
    id: 13,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 0
},
{
    id: 14,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 0
},
{
    id: 15,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 0
},
{
    id: 16,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 0
},
{
    id: 17,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 0
},
{
    id: 18,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 0
},
{
    id: 19,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 0
},
{
    id: 20,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 0
},
{
    id: 21,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 0
},
{
    id: 22,
    averageRating: 5,
    name: "Samsung A25",
    category: CATEGORY_ARTICLES[0],
    price: 500,
    date: new Date(),
    tags: ["smartphone", "samsung"],
    img: SamgsungA24,
    quantity: 0,
    nbSales: 0
},

]
