/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./pages/Account.vue')['default']
    AccountAdress: typeof import('./components/AccountAdress.vue')['default']
    AccountLastArticlesCheck: typeof import('./components/AccountLastArticlesCheck.vue')['default']
    AccountLinkToList: typeof import('./components/AccountLinkToList.vue')['default']
    AccountLinkToOrder: typeof import('./components/AccountLinkToOrder.vue')['default']
    AccountPersonalInformation: typeof import('./components/AccountPersonalInformation.vue')['default']
    ArticleChipGroup: typeof import('./components/ArticleChipGroup.vue')['default']
    ArticleComments: typeof import('./components/ArticleComments.vue')['default']
    ArticleDetail: typeof import('./pages/ArticleDetail.vue')['default']
    ArticleSearch: typeof import('./components/ArticleSearch.vue')['default']
    ArticleSearchChipGroup: typeof import('./components/ArticleSearchChipGroup.vue')['default']
    ArticleSearchCriteria: typeof import('./components/ArticleSearchCriteria.vue')['default']
    ArticleSearchResult: typeof import('./components/ArticleSearchResult.vue')['default']
    ArticleSheet: typeof import('./components/ArticleSheet.vue')['default']
    ArticlesSimilarities: typeof import('./components/ArticlesSimilarities.vue')['default']
    Cart: typeof import('./pages/Cart.vue')['default']
    CartEmpty: typeof import('./components/CartEmpty.vue')['default']
    CartFull: typeof import('./components/CartFull.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HistoricOrder: typeof import('./pages/HistoricOrder.vue')['default']
    HistoricOrderArticleAlreadyBuy: typeof import('./components/HistoricOrderArticleAlreadyBuy.vue')['default']
    HistoricOrderCommands: typeof import('./components/HistoricOrderCommands.vue')['default']
    Home: typeof import('./pages/Home.vue')['default']
    HomeBestSales: typeof import('./components/HomeBestSales.vue')['default']
    HomeCategory: typeof import('./components/HomeCategory.vue')['default']
    HomeNewArticle: typeof import('./components/HomeNewArticle.vue')['default']
    List: typeof import('./pages/List.vue')['default']
    ListAddNewList: typeof import('./components/ListAddNewList.vue')['default']
    ListArticles: typeof import('./components/ListArticles.vue')['default']
    ListCard: typeof import('./components/ListCard.vue')['default']
    ListDescription: typeof import('./components/ListDescription.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    Order: typeof import('./pages/Order.vue')['default']
    OrderAdress: typeof import('./components/OrderAdress.vue')['default']
    OrderCardArticles: typeof import('./components/OrderCardArticles.vue')['default']
    OrderForm: typeof import('./components/OrderForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchArticle: typeof import('./components/SearchArticle.vue')['default']
  }
}
